---
- name: Install docker Python SDK
  pip:
    name: docker
    executable: pip3

- name: Login to Docker Hub
  become_user: vagrant
  community.docker.docker_login:
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_pat_token }}"
