# -*- mode: ruby -*-
# vi: set ft=ruby :

ANSIBLE_REPO = "https://github.com/aljica/k3s-lab.git"

CONTROL_IP  = "192.168.56.10"
MASTER_IP   = "192.168.56.11"
WORKER1_IP  = "192.168.56.12"
WORKER2_IP  = "192.168.56.13"
DATABASE_IP = "192.168.56.14"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # --- VM 1: Ansible Control Node ---
  config.vm.define "control" do |ctrl|
    ctrl.vm.hostname = "control"
    ctrl.vm.network "private_network", ip: CONTROL_IP

    ctrl.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-control"
      vb.memory = 512
      vb.cpus   = 1
    end

    ctrl.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -y
      apt-get install -y software-properties-common
      add-apt-repository --yes --update ppa:ansible/ansible
      apt-get install -y ansible git docker.io

      # Add vagrant to docker group during provisioning
      usermod -aG docker vagrant

      sudo -u vagrant ssh-keygen -t rsa -b 2048 \
        -f /home/vagrant/.ssh/id_rsa -N "" 2>/dev/null || true

      cp /home/vagrant/.ssh/id_rsa.pub /vagrant/control_key.pub

      sudo -u vagrant git clone #{ANSIBLE_REPO} \
        /home/vagrant/k3s

      # Install Ansible collections from requirements.yml
      sudo -u vagrant ansible-galaxy collection install \
      -r /home/vagrant/k3s/ansible/requirements.yml

      echo "=== Control node ready ==="
    SHELL
  end

  # --- VM 2: K3s Master ---
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: MASTER_IP
    master.vm.network "forwarded_port", guest: 30000, host: 30000

    master.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-master"
      vb.memory = 2048
      vb.cpus   = 2
    end

    master.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control_key.pub \
        >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      echo "=== K3s master ready ==="
    SHELL
  end

  # --- VM 3: K3s Worker 1 ---
  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: WORKER1_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-worker1"
      vb.memory = 512
      vb.cpus   = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control_key.pub \
        >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      echo "=== K3s worker1 ready ==="
    SHELL
  end

  # --- VM 4: K3s Worker 2 ---
  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"
    worker.vm.network "private_network", ip: WORKER2_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-worker2"
      vb.memory = 512
      vb.cpus   = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control_key.pub \
        >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      echo "=== K3s worker2 ready ==="
    SHELL
  end

  # --- VM 5: PostgreSQL Database ---
  config.vm.define "database" do |db|
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: DATABASE_IP

    db.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-database"
      vb.memory = 512
      vb.cpus   = 1
    end

    db.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control_key.pub \
        >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      echo "=== Database ready ==="
    SHELL
  end

end