---
- name: Configure control node
  hosts: control
  become: yes
  vars_files:
    - /vagrant/secrets.yml
    - vars/vars.yml
  roles:
    - control

- name: Install K3s master
  hosts: master
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - k3s-master

- name: Install K3s workers
  hosts: workers
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - k3s-worker

- name: Configure database
  hosts: database
  become: yes
  vars_files:
    - /vagrant/secrets.yml
    - vars/vars.yml
  roles:
    - database

- name: Build and push Flask image
  hosts: control
  become: yes
  vars_files:
    - /vagrant/secrets.yml
    - vars/vars.yml
  roles:
    - k3s-manifests-build